###
curl "https://api.twitter.com/2/tweets/sample/stream" -H "Authorization: Bearer AAAAAAAAAAAAAAAAAAAAANr%2BggEAAAAAqmwaKslLoIJ7nANKHZc1Fqyobcc%3DpMVASQ1FFHr2boNhAij7mgdT13GvL7ii3PXuztbpzdgJFd3EOc"

###
curl "https://api.twitter.com/2/tweets/sample/stream" -H "Authorization: Bearer AAAAAAAAAAAAAAAAAAAAANr%2BggEAAAAAqmwaKslLoIJ7nANKHZc1Fqyobcc%3DpMVASQ1FFHr2boNhAij7mgdT13GvL7ii3PXuztbpzdgJFd3EOc"